# Generated by Django 5.2 on 2026-09-17 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='stars_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='trustpilot_invite_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1-5 stars', null=True)),
                ('route', models.CharField(choices=[('google', 'Google'), ('trustpilot', 'Trustpilot'), ('internal', 'Internal (managers)')], default='internal', max_length=20)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('callback_requested', models.BooleanField(default=False)),
                ('callback_phone', models.CharField(blank=True, default='', max_length=50)),
                ('feedback_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notified', models.BooleanField(default=False)),
                ('notified_with_feedback', models.BooleanField(default=False)),
                ('zoho_note_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoho_task_id', models.CharField(blank=True, default='', max_length=50)),
                ('zoho_error', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.reviewrequest')),
            ],
            options={
                'verbose_name': '⭐ Review',
                'verbose_name_plural': '⭐ Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
