# Generated by Django 5.2 on 2025-04-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbiApostilleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('country_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('package', models.CharField(choices=[('federal_standard', 'Federal Standard Service - $125'), ('expedited_federal', 'Expedited Federal Service - $195'), ('state_level', 'State-Level Service - $250')], max_length=50)),
                ('count', models.PositiveIntegerField(help_text='Price of $25 per apostille certificate')),
                ('shipping_option', models.CharField(choices=[('ups_ground', 'UPS Ground (Standard Shipping) - $0.00'), ('1day_express', '1-Day Domestic Express (Overnight) - $29.00'), ('2day_express', '2-Day Domestic Express - $19.00')], max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total Price', max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.fbiapostilleorder')),
            ],
        ),
    ]
