# Generated by Django 5.2 on 2025-04-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FbiPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_certificate', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='FbiServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AlterField(
            model_name='fbiapostilleorder',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.fbiservicepackage'),
        ),
        migrations.AlterField(
            model_name='fbiapostilleorder',
            name='shipping_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.shippingoption'),
        ),
    ]
