# Generated by Django 5.2 on 2025-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_fbipricingsettings_fbiservicepackage_shippingoption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbiapostilleorder',
            options={'verbose_name': 'FBI Apostille — Order', 'verbose_name_plural': 'FBI Apostille — Orders'},
        ),
        migrations.AlterModelOptions(
            name='fbipricingsettings',
            options={'verbose_name': 'FBI Apostille — Pricing Setting'},
        ),
        migrations.AlterModelOptions(
            name='fbiservicepackage',
            options={'verbose_name': 'FBI Apostille — Service Package', 'verbose_name_plural': 'FBI Apostille — Service Packages'},
        ),
        migrations.AddField(
            model_name='fbiapostilleorder',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
