# Generated by Django 5.2 on 2025-05-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_fbiapostilleorder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbiapostilleorder',
            name='count',
            field=models.PositiveIntegerField(help_text='Price per apostille certificate'),
        ),
    ]
