# Generated by Django 5.2 on 2025-06-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0004_alter_fbiapostilleorder_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriageOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('husband_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('wife_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('marriage_date', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated total price for this marriage order', max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarriagePricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=100.0, help_text='Base price (USD) for one Triple Seal Marriage order', max_digits=8)),
            ],
            options={
                'verbose_name': 'Marriage Pricing Setting',
                'verbose_name_plural': 'Marriage Pricing Settings',
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='orders/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
