# Generated by Django 5.2 on 2025-06-01 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_marriageorder_marriagepricingsettings_fileattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileattachment',
            options={'verbose_name': 'File Attachment', 'verbose_name_plural': 'File Attachments'},
        ),
        migrations.AlterModelOptions(
            name='marriageorder',
            options={'verbose_name': 'Triple Seal Marriage Order', 'verbose_name_plural': 'Triple Seal Marriage Orders'},
        ),
    ]
