# Generated by Django 5.2 on 2025-06-06 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_orderfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriageorder',
            options={'verbose_name': 'Triple Seal Marriage — Order', 'verbose_name_plural': 'Triple Seal Marriage — Orders'},
        ),
        migrations.AlterModelOptions(
            name='marriagepricingsettings',
            options={'verbose_name': 'Triple Seal Marriage — Pricing Setting', 'verbose_name_plural': 'Triple Seal Marriage — Pricing Settings'},
        ),
    ]
