# Generated by Django 5.2 on 2025-06-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_add_marriage_certificate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marriageorder',
            old_name='marriage_certificate_number',
            new_name='marriage_number',
        ),
    ]
