# Generated by Django 5.2 on 2025-06-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_marriage_certificate_number_marriageorder_marriage_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbiapostilleorder',
            name='zoho_synced',
            field=models.BooleanField(default=False),
        ),
    ]
