# Generated by Django 5.2 on 2025-06-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_fbiapostilleorder_zoho_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbassyLegalizationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('document_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Embassy Legalization — Order',
                'verbose_name_plural': 'Embassy Legalization — Orders',
            },
        ),
    ]
