# Generated by Django 5.2 on 2025-06-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_embassylegalizationorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('languages', models.TextField(help_text='Selected languages as comma-separated list')),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Translation — Order',
                'verbose_name_plural': 'Translation — Orders',
            },
        ),
    ]
