# Generated by Django 5.2 on 2025-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_translationorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApostilleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(help_text='Type of documents', max_length=255)),
                ('country', models.CharField(help_text='Country of legalization', max_length=100)),
                ('service_type', models.CharField(help_text='Service location type: Office, UPS, or My Address', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Client address, if applicable', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Apostille — Order',
                'verbose_name_plural': 'Apostille — Orders',
            },
        ),
        migrations.AlterModelOptions(
            name='fileattachment',
            options={'verbose_name': '⚙️ File Attachment', 'verbose_name_plural': '⚙️ File Attachments'},
        ),
        migrations.AlterModelOptions(
            name='shippingoption',
            options={'verbose_name': '⚙️ Shipping Option', 'verbose_name_plural': '⚙️ Shipping Options'},
        ),
    ]
