# Generated by Django 5.2 on 2025-06-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_apostilleorder_alter_fileattachment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='I9VerificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'I-9 Verification — Order',
                'verbose_name_plural': 'I-9 Verification — Orders',
            },
        ),
    ]
