# Generated by Django 5.2 on 2025-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_i9verificationorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='i9verificationorder',
            name='appointment_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='i9verificationorder',
            name='appointment_time',
            field=models.CharField(),
        ),
    ]
