# Generated by Django 5.2 on 2025-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_i9verificationorder_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marriageorder',
            name='zoho_synced',
            field=models.BooleanField(default=False),
        ),
    ]
