# Generated by Django 5.2 on 2025-07-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_marriageorder_zoho_synced'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('appointment_date', models.CharField(max_length=50)),
                ('appointment_time', models.CharField(max_length=50)),
                ('services', models.TextField(help_text='Comma-separated list of selected services')),
                ('address', models.TextField(blank=True, help_text='Client address, if applicable', null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Quote — Request',
                'verbose_name_plural': 'Quote — Requests',
            },
        ),
    ]
