# Generated by Django 5.2 on 2025-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_quoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='number',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
