# Generated by Django 5.2 on 2025-07-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_quoterequest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoterequest',
            name='services',
            field=models.TextField(help_text='selected service'),
        ),
    ]
