# Generated by Django 5.2 on 2025-10-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_quoterequest_services'),
        ('orders', '0021_track_alter_quoterequest_services'),
    ]

    operations = [
    ]
