# Generated by Django 5.2 on 2025-10-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_merge_20251020_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='track',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='track',
            name='email',
        ),
        migrations.RemoveField(
            model_name='track',
            name='name',
        ),
        migrations.AddField(
            model_name='track',
            name='data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='service',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
