# Generated by Django 5.2 on 2025-11-25 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_track_comment_remove_track_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbiapostilleorder',
            name='manager_notified',
            field=models.BooleanField(default=False, help_text='Manager email sent'),
        ),
        migrations.AddField(
            model_name='fbiapostilleorder',
            name='tid_created',
            field=models.BooleanField(default=False, help_text='Tracking ID created'),
        ),
        migrations.AddField(
            model_name='fbiapostilleorder',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fbi_orders', to='orders.track'),
        ),
        migrations.AddField(
            model_name='marriageorder',
            name='manager_notified',
            field=models.BooleanField(default=False, help_text='Manager email sent'),
        ),
        migrations.AddField(
            model_name='marriageorder',
            name='tid_created',
            field=models.BooleanField(default=False, help_text='Tracking ID created'),
        ),
        migrations.AddField(
            model_name='marriageorder',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marriage_orders', to='orders.track'),
        ),
    ]
