# Generated by Django 5.2 on 2026-02-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_add_attribution_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCallLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatconverts_lead_id', models.CharField(db_index=True, help_text='WhatConverts lead_id', max_length=100, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('contact_company', models.CharField(blank=True, max_length=255)),
                ('call_duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('call_recording_url', models.URLField(blank=True, null=True)),
                ('lead_score', models.IntegerField(blank=True, help_text='WhatConverts lead score', null=True)),
                ('lead_status', models.CharField(blank=True, help_text='WhatConverts lead status', max_length=50)),
                ('detected_service', models.CharField(blank=True, help_text='Auto-detected service from landing URL', max_length=100)),
                ('landing_url', models.URLField(blank=True)),
                ('lead_url', models.URLField(blank=True, help_text='Page where lead was generated')),
                ('source', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=255)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('gclid', models.CharField(blank=True, help_text='Google Click ID', max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_make', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('lead_summary', models.TextField(blank=True, help_text='AI-generated summary')),
                ('sentiment', models.CharField(blank=True, help_text='Positive/Negative/Neutral', max_length=50)),
                ('intent', models.TextField(blank=True, help_text='Detected intent')),
                ('spotted_keywords', models.CharField(blank=True, max_length=500)),
                ('raw_webhook_data', models.JSONField(help_text='Complete WhatConverts webhook payload')),
                ('zoho_synced', models.BooleanField(default=False)),
                ('zoho_lead_id', models.CharField(blank=True, help_text='Zoho Lead/Deal ID', max_length=100)),
                ('zoho_attribution_id', models.CharField(blank=True, help_text='Zoho Attribution Record ID', max_length=100)),
                ('zoho_module', models.CharField(blank=True, help_text='Target Zoho module (FBI_Apostille, etc)', max_length=100)),
                ('matched_with_form', models.BooleanField(default=False, help_text='Matched with web form submission')),
                ('matched_order_type', models.CharField(blank=True, max_length=100)),
                ('matched_order_id', models.IntegerField(blank=True, null=True)),
                ('whatconverts_created_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phone Call Lead',
                'verbose_name_plural': 'Phone Call Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
