# Generated by Django 5.2 on 2026-02-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_phonecalllead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecalllead',
            name='call_recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='phonecalllead',
            name='landing_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='phonecalllead',
            name='lead_url',
            field=models.URLField(blank=True, help_text='Page where lead was generated', max_length=500),
        ),
    ]
