# Generated by Django 5.2 on 2026-03-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_extend_url_fields_to_500'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreCheckSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('document_type', models.CharField(help_text='Type of document for pre-check review', max_length=255)),
                ('destination_country', models.CharField(help_text='Country where the document is intended for', max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('attribution_data', models.JSONField(blank=True, help_text='Marketing attribution data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pre-Check — Submission',
                'verbose_name_plural': 'Pre-Check — Submissions',
            },
        ),
    ]
