# Generated by Django 5.2 on 2026-03-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_add_precheck_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerprintingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('preferred_date', models.CharField(max_length=50)),
                ('preferred_time', models.CharField(max_length=50)),
                ('service_location', models.CharField(choices=[('Office', 'Office'), ('Mobile', 'Mobile')], max_length=20)),
                ('address', models.TextField(blank=True, help_text='Required for mobile service', null=True)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('attribution_data', models.JSONField(blank=True, help_text='Marketing attribution data', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fingerprinting — Submission',
                'verbose_name_plural': 'Fingerprinting — Submissions',
            },
        ),
    ]
