# Generated by Django 5.2 on 2026-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_add_fingerprinting_submission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbiservicepackage',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'FBI Apostille — Service Package', 'verbose_name_plural': 'FBI Apostille — Service Packages'},
        ),
        migrations.AddField(
            model_name='fbiservicepackage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower number = shown first on frontend'),
        ),
    ]
