# Generated by Django 5.2 on 2026-04-02 19:41

from django.db import migrations


def set_sort_order(apps, schema_editor):
    FbiServicePackage = apps.get_model('orders', 'FbiServicePackage')
    order_map = {
        'expedited_federal': 0,
        'federal_standard': 1,
        'state_level': 2,
    }
    for pkg in FbiServicePackage.objects.all():
        pkg.sort_order = order_map.get(pkg.code, 99)
        pkg.save(update_fields=['sort_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_add_sort_order_to_fbi_package'),
    ]

    operations = [
        migrations.RunPython(set_sort_order, migrations.RunPython.noop),
    ]
