# Generated by Django 5.2 on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_set_default_package_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprintingsubmission',
            name='service_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('fbi', 'FBI Departmental Order Live Scan'),
                    ('fd258', 'FD-258 Print-to-Card Fingerprinting'),
                    ('fdle', 'FDLE Fingerprinting (Florida)'),
                    ('atf', 'ATF Fingerprinting'),
                ],
                help_text='Which fingerprinting service the client needs (for quote)',
                max_length=20,
            ),
        ),
    ]
