# Generated by Django 5.2 on 2026-09-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_quote_request_deduplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(choices=[('business_account', 'Business Account'), ('partner', 'Partner')], db_index=True, max_length=32)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('organization', models.CharField(help_text='Organization (business account) / Company (partner)', max_length=255)),
                ('role', models.CharField(blank=True, help_text='Business account: contact role/title', max_length=255)),
                ('website', models.CharField(blank=True, help_text='Partner: company website', max_length=500)),
                ('location', models.CharField(blank=True, help_text='city_state (business account) / state_country (partner)', max_length=255)),
                ('org_type', models.CharField(blank=True, help_text='org_type (business account) / business_type (partner)', max_length=255)),
                ('services', models.JSONField(blank=True, default=list, help_text='Selected service keys')),
                ('volume', models.CharField(blank=True, help_text='order_frequency (business account) / monthly_volume (partner)', max_length=255)),
                ('start_timing', models.CharField(blank=True, max_length=255)),
                ('countries', models.CharField(blank=True, max_length=500)),
                ('delivery_preference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('partner_terms_ack', models.BooleanField(default=False)),
                ('source_page', models.CharField(blank=True, max_length=500)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('attribution_data', models.JSONField(blank=True, help_text='Marketing attribution data (DCMNTracker)', null=True)),
                ('raw_payload', models.JSONField(blank=True, help_text='Full JSON payload as received', null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('zoho_synced', models.BooleanField(default=False)),
                ('zoho_lead_id', models.CharField(blank=True, help_text='Zoho Leads record ID', max_length=100)),
                ('email_sent', models.BooleanField(default=False, help_text='Manager notification email sent')),
                ('client_email_sent', models.BooleanField(default=False, help_text='Confirmation email sent to the applicant')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'B2B — Application (Business Account / Partner)',
                'verbose_name_plural': 'B2B — Applications (Business Account / Partner)',
                'ordering': ['-created_at'],
            },
        ),
    ]
